import { Container } from '@/components/site/container';
import { Footer } from '@/components/site/footer';
import { Navbar } from '@/components/site/navbar';
import { Shield } from 'lucide-react';
import Link from 'next/link';

export const metadata = {
  title: 'Privacy Policy — FieldLoop',
  description:
    'How FieldLoop collects, uses and safeguards your data across our agritech platform.',
  openGraph: {
    title: 'Privacy Policy — FieldLoop',
    description:
      'How FieldLoop collects, uses and safeguards your data across our agritech platform.',
    url: 'https://www.fieldloop.org/privacy',
  },
  alternates: {
    canonical: 'https://www.fieldloop.org/privacy',
  },
};

const sections = [
  {
    h: '1. Information we collect',
    p: 'We collect information you provide directly (name, email, farm details), data generated by your use of FieldLoop sensors and dashboards, and limited technical data such as device type and IP address.',
  },
  {
    h: '2. How we use information',
    p: 'Your data powers personalised insights, agronomic recommendations, customer support, security, and product improvements. We never sell personal data to third parties.',
  },
  {
    h: '3. Sharing',
    p: 'We share data only with processors that help us operate (hosting, analytics, payments) under strict data-protection agreements, or when required by law.',
  },
  {
    h: '4. Storage & security',
    p: 'Data is encrypted in transit and at rest. Field telemetry is stored within ECOWAS-approved regions where possible, with role-based access for our team.',
  },
  {
    h: '5. Your rights',
    p: 'You can request access, correction, export, or deletion of your data at any time by emailing privacy@fieldloop.africa.',
  },
  {
    h: '6. Updates',
    p: 'We will notify you in-app and by email of material changes to this policy at least 14 days before they take effect.',
  },
];

export default function PrivacyPage() {
  return (
    <div className='min-h-screen bg-background'>
      <Navbar />
      <main className='pt-32 pb-24'>
        <Container>
          <div className='mx-auto max-w-3xl'>
            <Link
              href='/'
              className='text-xs uppercase tracking-[0.2em] text-muted-foreground hover:text-foreground'
            >
              ← Back home
            </Link>
            <div className='mt-6 flex items-center gap-3'>
              <span className='grid size-11 place-items-center rounded-full bg-leaf-50 text-leaf-700'>
                <Shield className='size-5' />
              </span>
              <p className='text-xs uppercase tracking-[0.22em] text-leaf-700'>
                Legal
              </p>
            </div>
            <h1 className='mt-4 text-4xl md:text-5xl text-balance'>
              Privacy Policy
            </h1>
            <p className='mt-3 text-sm text-muted-foreground'>
              Last updated:{' '}
              {new Date().toLocaleDateString('en-GB', {
                day: 'numeric',
                month: 'long',
                year: 'numeric',
              })}
            </p>

            <div className='mt-12 space-y-10'>
              {sections.map((s) => (
                <section key={s.h}>
                  <h2 className='text-xl font-semibold tracking-tight text-foreground'>
                    {s.h}
                  </h2>
                  <p className='mt-3 leading-relaxed text-muted-foreground'>
                    {s.p}
                  </p>
                </section>
              ))}
            </div>

            <div className='mt-16 rounded-2xl border border-border bg-leaf-50/60 p-6'>
              <h3 className='font-semibold text-leaf-900'>Questions?</h3>
              <p className='mt-2 text-sm text-ink-soft'>
                Reach our Data Protection Officer at{' '}
                <a className='underline' href='mailto:privacy@fieldloop.africa'>
                  privacy@fieldloop.africa
                </a>
                .
              </p>
            </div>
          </div>
        </Container>
      </main>
      <Footer />
    </div>
  );
}
